
# -------
# Helpers
# -------

"""
Color dictionary

source: matplotlib.colors.cnames
"""
COLORS = ['aliceblue', 'antiquewhite', 'aqua', 'aquamarine', 'azure', 'beige',
          'bisque', 'black', 'blanchedalmond', 'blue', 'blueviolet', 'brown',
          'burlywood', 'cadetblue', 'chartreuse', 'chocolate', 'coral',
          'cornflowerblue', 'cornsilk', 'crimson', 'cyan', 'darkblue',
          'darkcyan', 'darkgoldenrod', 'darkgray', 'darkgreen', 'darkkhaki',
          'darkmagenta', 'darkolivegreen', 'darkorange', 'darkorchid',
          'darkred', 'darksalmon', 'darkseagreen', 'darkslateblue',
          'darkslategray', 'darkturquoise', 'darkviolet', 'deeppink',
          'deepskyblue', 'dimgray', 'dodgerblue', 'firebrick', 'floralwhite',
          'forestgreen', 'fuchsia', 'gainsboro', 'ghostwhite', 'gold',
          'goldenrod', 'gray', 'green', 'greenyellow', 'honeydew', 'hotpink',
          'indianred', 'indigo', 'ivory', 'khaki', 'lavender', 'lavenderblush',
          'lawngreen', 'lemonchiffon', 'lightblue', 'lightcoral', 'lightcyan',
          'lightgoldenrodyellow', 'lightgreen', 'lightgray', 'lightpink',
          'lightsalmon', 'lightseagreen', 'lightskyblue', 'lightslategray',
          'lightsteelblue', 'lightyellow', 'lime', 'limegreen', 'linen',
          'magenta', 'maroon', 'mediumaquamarine', 'mediumblue',
          'mediumorchid', 'mediumpurple', 'mediumseagreen', 'mediumslateblue',
          'mediumspringgreen', 'mediumturquoise', 'mediumvioletred',
          'midnightblue', 'mintcream', 'mistyrose', 'moccasin', 'navajowhite',
          'navy', 'oldlace', 'olive', 'olivedrab', 'orange', 'orangered',
          'orchid', 'palegoldenrod', 'palegreen', 'paleturquoise',
          'palevioletred', 'papayawhip', 'peachpuff', 'peru', 'pink', 'plum',
          'powderblue', 'purple', 'red', 'rosybrown', 'royalblue',
          'saddlebrown', 'salmon', 'sandybrown', 'seagreen', 'seashell',
          'sienna', 'silver', 'skyblue', 'slateblue', 'slategray', 'snow',
          'springgreen', 'steelblue', 'tan', 'teal', 'thistle', 'tomato',
          'turquoise', 'violet', 'wheat', 'white', 'whitesmoke', 'yellow',
          'yellowgreen']

"""
Extra colors that were found on Oxygen Boutique store to extend the main
color dictionary.
"""
EXTRA_COLORS = ['cranberry', 'mango', 'denim', 'coral', 'chambray', 'mint']

COLORS = COLORS + EXTRA_COLORS

"""
This dictionary could be more reliable if it was generated by analysing all the
words in all the item's descriptions, then calculating which are the less
common (e.g.) thus assigning them more weigth.

And I have to confess this was the hardest part of the task... I'm really not
well familiarized with women's clothing (not even in my native language) and
categorizing everything was quite a process hehe.

'A' apparel
'S' shoes
'B' bags
'J' jewelry
'R' accessories
"""
ITEM_DICT = {
    'accessories': {'type': 'R', 'weigth': 10},
    'ankle': {'type': 'S', 'weigth': 10},
    'bag': {'type': 'B', 'weigth': 10},
    'bags': {'type': 'B', 'weigth': 10},
    'bangle': {'type': 'R', 'weigth': 10},
    'bangles': {'type': 'R', 'weigth': 10},
    'bikini': {'type': 'A', 'weigth': 5},
    'blouse': {'type': 'A', 'weigth': 5},
    'boots': {'type': 'S', 'weigth': 10},
    'bottom': {'type': 'A', 'weigth': 5},
    'bottoms': {'type': 'A', 'weigth': 5},
    'bracelet': {'type': 'J', 'weigth': 10},
    'bracelets': {'type': 'J', 'weigth': 10},
    'brogue': {'type': 'S', 'weigth': 10},
    'brogues': {'type': 'S', 'weigth': 10},
    'candle': {'type': 'R', 'weigth': 10},
    'case': {'type': 'R', 'weigth': 10},
    'coat': {'type': 'A', 'weigth': 10},
    'clothing': {'type': 'A', 'weigth': 10},
    'coverup': {'type': 'A', 'weigth': 10},
    'dress': {'type': 'A', 'weigth': 5},
    'dresses': {'type': 'A', 'weigth': 5},
    'earrings': {'type': 'J', 'weigth': 10},
    'feet': {'type': 'S', 'weigth': 10},
    'footwear': {'type': 'S', 'weigth': 10},
    'gown': {'type': 'A', 'weigth': 10},
    'hats': {'type': 'R', 'weigth': 10},
    'heels': {'type': 'S', 'weigth': 10},
    'jacket': {'type': 'A', 'weigth': 10},
    'jupe': {'type': 'A', 'weigth': 10},
    'jumper': {'type': 'A', 'weigth': 10},
    'lenses': {'type': 'R', 'weigth': 5},
    'necklace': {'type': 'J', 'weigth': 10},
    'necklaces': {'type': 'J', 'weigth': 10},
    'nightshirt': {'type': 'A', 'weigth': 10},
    'outerwear': {'type': 'A', 'weigth': 10},
    'pants': {'type': 'A', 'weigth': 10},
    'ring': {'type': 'J', 'weigth': 10},
    'rings': {'type': 'J', 'weigth': 10},
    'romper': {'type': 'A', 'weigth': 10},
    'rompers': {'type': 'A', 'weigth': 10},
    'jumpsuit': {'type': 'A', 'weigth': 10},
    'jumpsuits': {'type': 'A', 'weigth': 10},
    'playsuit': {'type': 'A', 'weigth': 10},
    'pyjama': {'type': 'A', 'weigth': 10},
    'pyjamas': {'type': 'A', 'weigth': 10},
    'pumps': {'type': 'S', 'weigth': 10},
    'sandal': {'type': 'S', 'weigth': 10},
    'sandals': {'type': 'S', 'weigth': 10},
    'shorts': {'type': 'A', 'weigth': 10},
    'scents': {'type': 'R', 'weigth': 10},
    'slipper': {'type': 'S', 'weigth': 10},
    'shoes': {'type': 'S', 'weigth': 10},
    'sneakers': {'type': 'S', 'weigth': 10},
    'shirt': {'type': 'A', 'weigth': 10},
    'skinnies': {'type': 'A', 'weigth': 10},
    'skirt': {'type': 'A', 'weigth': 10},
    'soludos': {'type': 'S', 'weigth': 5},
    'stilettos': {'type': 'S', 'weigth': 10},
    'sunglasses': {'type': 'R', 'weigth': 10},
    'sweater': {'type': 'A', 'weigth': 10},
    'sweatshirt': {'type': 'A', 'weigth': 10},
    'swimwear': {'type': 'A', 'weigth': 10},
    'swimsuit': {'type': 'A', 'weigth': 10},
    'tattoo': {'type': 'R', 'weigth': 10},
    'tee': {'type': 'A', 'weigth': 10},
    'top': {'type': 'A', 'weigth': 5},
    'tops': {'type': 'A', 'weigth': 5},
    'tank': {'type': 'A', 'weigth': 10},
    'tunic': {'type': 'A', 'weigth': 10},
    'waistcoat': {'type': 'A', 'weigth': 10},
    'wedges': {'type': 'S', 'weigth': 10},
}

# Currency value on the www.oxygenboutique.com/Currency.aspx form
CURRENCY_CODE = {'usd': '503329C6-40CB-47E6-91D1-9F11AF63F706',
                 'eur': 'b2dd6e5d-5336-4195-b966-2c81d2b34897',
                 'gbp': 'b2dd6e5d-5336-4195-b966-2c81d2b34899'}

# Session cookie values for each currency
SESSION_COOKIE = {'usd': 'edg33cbz3q1la3b2up5alxx0',
                  'gbp': 'qml5ureyqasgtdeoxsooazr5',
                  'eur': 'z0f21xla2mvroac2s0qtzcv4'}
